import * as Cesium from 'cesium';
import { ModeCollection, elementType, TransformerConstructorOptions } from './type';
export default class Transformer {
    scene: Cesium.Scene;
    element: elementType;
    private boundingSphere;
    private elementCenterRelativeBoundingSphere;
    private elementCachedRotationMatrix;
    elementCachedScaleMatrix: Cesium.Matrix4;
    private cachedCenter;
    private center;
    private handler;
    private activeAxis;
    private activeAxisType;
    private gizmo;
    private mode;
    private intersectStartPoint;
    private intersectEndPoint;
    private pointPrimitiveCollection;
    private plane;
    private onMouseDown;
    private onMouseUp;
    private onMouseMove;
    private keyEvent;
    constructor({ scene, element, boundingSphere }: TransformerConstructorOptions);
    get isDetoryed(): boolean;
    private init;
    changeMode(mode: ModeCollection): void;
    private applyLinearMatrixToGizmo;
    private createPlane;
    private updatePlane;
    private getActiveAxisFromMouse;
    private updateBoundingSphere;
    private linearTransformAroundCenter;
    private updateTranslation;
    private updateRotation;
    private updateScale;
    private getPointToCenterRay;
    private mouseDown;
    private mouseUp;
    private mouseMove;
    private registerHandler;
    destory(): void;
    private detoryHandler;
}
